name: workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency_check:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build Docker Image
        run: |
          docker build -t my_ml_project .

      - name: Run Dependency Check
        run: |
          docker run --rm -v $PWD:/app my_ml_project pip check

